main:
  heroTitle: "North Hampshire Repair Café"
  heroSubtitle: "A team of talented repairers repairing & recycling as much as we can"
  scrollBannerText: "Hook August 29th 10-12:30"
  scrollBannerHref: "#next-event"
  nextEventDescription: "Our end of the month event on Saturday 29th August. Online booking closes the day before. You're still welcome to come along and book in on the day at 10:30. We have been getting busy so please be patient, sit back and enjoy the coffee."
  stats:
    happyClients: 2399
    savingsGbp: 111895
    ghgKg: 19260
    landfillKg: 2980
  contactEmail: info@nhrc.uk
  facebookUrl: "https://www.facebook.com/North-Hampshire-Repair-Cafe-112080698146905"
  instagramUrl: "https://instagram.com/nhrc.uk"
  paypalHostedButtonId: JB878XJDL68LS
  statcounterProject: 12753477
  statcounterSecurity: 6ce90cbc
  gtagId: G-YJ0QM38Y1C
