name: Build site

on:
  push:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build the website

    steps:
      - uses: actions/checkout@v6
      - uses: peaceiris/actions-gh-pages@v4 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
